### ISSUE TITLE
Skyscraper does not build with Qt 5.15.0

### ISSUE THREAD

**Issue by igno2k** [muldjord/skyscraper#242]
**Describe the bug**
Skyscraper will not build with the newest Qt version 5.15.0 under Arch Linux. Building with 5.14.x works fine.

**To Reproduce**
Build with current Qt version.

**Terminal output**
`g++ -c -pipe -std=c++11 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -D_REENTRANT -fPIC -DVERSION=\"3.5.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o fxrounded.o src/fxrounded.cpp
src/fxrounded.cpp: In member function ‘QImage FxRounded::applyEffect(const QImage&, const Layer&)’:
src/fxrounded.cpp:46:16: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
   46 |   QPainterPath path;
      |                ^~~~
make: *** [Makefile:1170: fxrounded.o] Error 1`

The package under Arch Linux I have downgraded is named `qt5-base`

**Comment by muldjord** [comment]
Could you try adding `#include <QPainterPath>` just after `#include <QPainter>` in the file `src/fxrounded.cpp` and then do `make` again? That should fix it and I will include that fix in the next release. Thanks for letting me know.

**Comment by igno2k** [comment]
Thanks, thats it! It's working fine now.

**Comment by muldjord** [comment]
Thanks for testing
